
# 邮箱发送配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/XingYi-Tech?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19960320
# application mappers
mybatis:
  configuration:
    aggressive-lazy-loading: false
    lazy-loading-enabled: false
    cache-enabled: false
    multiple-result-sets-enabled: true
    auto-mapping-behavior: full
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-column-label: true
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath*:mapper/*Mapper.xml
  type-aliases-package: com.xyzh.usermanager.entity
  type-handlers-package: com.xyzh.usermanager.mapper.typehandler
pagehelper:
  helper-dialect: mysql

server:
  port: 3000
